---
- hosts: loadbalancer
  become: true
  tasks:
  - name: install nginx
    apt: name=nginx state=present update_cache=yes
  - name: start_service
    service: 
     name=nginx
     state=started
     enabled=yes  